import React, { useEffect, useState } from "react";
import axios from "axios";
import { FaSearch, FaRobot, FaTag, FaCheck, FaClock, FaSyncAlt, FaBolt, FaCog } from "react-icons/fa";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const API = import.meta.env.VITE_API_URI;

const getToken = () =>
  localStorage.getItem("adminAccessToken") ||
  localStorage.getItem("adminToken") ||
  localStorage.getItem("adminRefreshToken") ||
  localStorage.getItem("accessToken");

const AdminSeoAi = () => {
  const [tab, setTab] = useState("seo");
  const [seoStats, setSeoStats] = useState(null);
  const [embedStats, setEmbedStats] = useState(null);
  const [seoProducts, setSeoProducts] = useState([]);
  const [search, setSearch] = useState("");
  const [generating, setGenerating] = useState(false);
  const [forceGenerating, setForceGenerating] = useState(false);
  const [embedGenerating, setEmbedGenerating] = useState(false);
  const [regeneratingId, setRegeneratingId] = useState(null);

  useEffect(() => {
    fetchSeoStats();
    fetchEmbedStats();
    fetchSeoProducts();
  }, []);

  const fetchSeoStats = async () => {
    try {
      const res = await axios.get(`${API}/api/seo/stats`, {
        headers: { Authorization: `Bearer ${getToken()}` },
      });
      setSeoStats(res.data);
    } catch {}
  };

  const fetchEmbedStats = async () => {
    try {
      const res = await axios.get(`${API}/api/embeddings/stats`, {
        headers: { Authorization: `Bearer ${getToken()}` },
      });
      setEmbedStats(res.data);
    } catch {}
  };

  const fetchSeoProducts = async () => {
    try {
      const res = await axios.get(`${API}/api/products`, {
        headers: { Authorization: `Bearer ${getToken()}` },
        params: { limit: 50 },
      });
      const list = Array.isArray(res.data) ? res.data : res.data?.products || [];
      setSeoProducts(list);
    } catch {}
  };

  const filteredProducts = seoProducts.filter((p) =>
    p.name?.toLowerCase().includes(search.toLowerCase())
  );

  const hasSeo = (p) => p.seo?.metaTitle && p.seo?.autoGenerated;
  const seoAge = (p) => {
    if (!p.seo?.lastGenerated) return "Never";
    const d = new Date(p.seo.lastGenerated);
    const now = new Date();
    const diff = now - d;
    const hours = Math.floor(diff / 3600000);
    if (hours < 1) return "Just now";
    if (hours < 24) return `${hours}h ago`;
    return `${Math.floor(hours / 24)}d ago`;
  };

  const handleGenerateSeo = async () => {
    setGenerating(true);
    try {
      const res = await axios.post(
        `${API}/api/seo/generate`,
        {},
        { headers: { Authorization: `Bearer ${getToken()}` } }
      );
      toast.success(`✅ SEO generated for ${res.data.count} products`);
      fetchSeoStats();
      fetchSeoProducts();
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed");
    } finally {
      setGenerating(false);
    }
  };

  const handleForceSeo = async () => {
    if (
      !confirm(
        "Force-regenerate SEO for ALL products?\n\nThis will use AI API credits and overwrite existing SEO."
      )
    )
      return;
    setForceGenerating(true);
    try {
      const res = await axios.post(
        `${API}/api/seo/force`,
        {},
        { headers: { Authorization: `Bearer ${getToken()}` } }
      );
      toast.success(`✅ Force-regenerated SEO for ${res.data.count} products`);
      fetchSeoStats();
      fetchSeoProducts();
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed");
    } finally {
      setForceGenerating(false);
    }
  };

  const handleRegenerateProduct = async (productId) => {
    setRegeneratingId(productId);
    try {
      const res = await axios.post(
        `${API}/api/seo/product/${productId}`,
        {},
        { headers: { Authorization: `Bearer ${getToken()}` } }
      );
      toast.success(`✅ SEO updated for ${res.data.seo?.metaTitle || "product"}`);
      fetchSeoProducts();
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed");
    } finally {
      setRegeneratingId(null);
    }
  };

  const handleGenerateEmbeddings = async () => {
    setEmbedGenerating(true);
    try {
      const res = await axios.post(
        `${API}/api/embeddings/generate`,
        {},
        { headers: { Authorization: `Bearer ${getToken()}` } }
      );
      toast.success(`✅ Generated ${res.data.count} embeddings`);
      fetchEmbedStats();
    } catch (err) {
      toast.error(err?.response?.data?.message || "Failed");
    } finally {
      setEmbedGenerating(false);
    }
  };

  return (
    <div className="p-4 sm:p-6 min-h-screen bg-gray-50">
      <ToastContainer position="top-center" />
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
            <FaCog className="text-white text-lg" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">AI & SEO</h1>
            <p className="text-sm text-gray-500">
              Manage AI-powered search embeddings and product SEO metadata
            </p>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-1 mb-6 bg-white rounded-xl p-1 shadow-sm border border-gray-200">
          <button
            onClick={() => setTab("seo")}
            className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-semibold transition ${
              tab === "seo"
                ? "bg-emerald-500 text-white shadow-md"
                : "text-gray-600 hover:bg-gray-100"
            }`}
          >
            <FaTag /> SEO Metadata
          </button>
          <button
            onClick={() => setTab("embeddings")}
            className={`flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-sm font-semibold transition ${
              tab === "embeddings"
                ? "bg-indigo-500 text-white shadow-md"
                : "text-gray-600 hover:bg-gray-100"
            }`}
          >
            <FaRobot /> AI Embeddings
          </button>
        </div>

        {/* ─── SEO TAB ──────────────────────────────────────── */}
        {tab === "seo" && (
          <div className="space-y-6">
            {/* SEO Stats */}
            <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4">
                <div className="text-2xl font-bold text-gray-900">{seoStats?.total || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">Total Products</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-green-200 p-4">
                <div className="text-2xl font-bold text-green-600">{seoStats?.withSEO || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">With SEO</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-orange-200 p-4">
                <div className="text-2xl font-bold text-orange-600">{seoStats?.pending || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">Pending</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 flex flex-col justify-center">
                <div className="flex gap-2">
                  <button
                    onClick={handleGenerateSeo}
                    disabled={generating}
                    className="flex-1 px-3 py-2 bg-emerald-500 text-white rounded-lg text-xs font-medium hover:bg-emerald-600 transition disabled:opacity-50 flex items-center justify-center gap-1"
                  >
                    <FaSyncAlt className={generating ? "animate-spin" : ""} />
                    {generating ? "..." : "Generate Pending"}
                  </button>
                  <button
                    onClick={handleForceSeo}
                    disabled={forceGenerating}
                    className="px-3 py-2 bg-orange-500 text-white rounded-lg text-xs font-medium hover:bg-orange-600 transition disabled:opacity-50 flex items-center gap-1"
                  >
                    <FaBolt className={forceGenerating ? "animate-pulse" : ""} />
                    {forceGenerating ? "..." : "Force All"}
                  </button>
                </div>
              </div>
            </div>

            {/* Product SEO Table */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <div className="p-4 border-b border-gray-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                <h2 className="font-semibold text-gray-900">Product SEO Status</h2>
                <div className="relative w-full sm:w-64">
                  <FaSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 text-sm" />
                  <input
                    type="text"
                    placeholder="Search products..."
                    value={search}
                    onChange={(e) => setSearch(e.target.value)}
                    className="w-full pl-9 pr-3 py-1.5 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-400 focus:border-transparent"
                  />
                </div>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
                    <tr>
                      <th className="px-4 py-3 text-left">Product</th>
                      <th className="px-4 py-3 text-left">Meta Title</th>
                      <th className="px-4 py-3 text-center">Status</th>
                      <th className="px-4 py-3 text-center">Generated</th>
                      <th className="px-4 py-3 text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100">
                    {filteredProducts.length === 0 ? (
                      <tr>
                        <td colSpan={5} className="px-4 py-8 text-center text-gray-400">
                          {search ? "No products match your search" : "Loading products..."}
                        </td>
                      </tr>
                    ) : (
                      filteredProducts.map((p) => (
                        <tr key={p._id} className="hover:bg-gray-50 transition-colors">
                          <td className="px-4 py-3">
                            <div className="flex items-center gap-3">
                              <img
                                src={p.mainImage || "/placeholder.jpg"}
                                alt=""
                                className="w-8 h-8 object-contain rounded bg-gray-100"
                              />
                              <span className="font-medium text-gray-900 line-clamp-1">
                                {p.name}
                              </span>
                            </div>
                          </td>
                          <td className="px-4 py-3 max-w-[200px]">
                            <span className="text-gray-600 text-xs line-clamp-1">
                              {p.seo?.metaTitle || "—"}
                            </span>
                          </td>
                          <td className="px-4 py-3 text-center">
                            {hasSeo(p) ? (
                              <span className="inline-flex items-center gap-1 text-green-600 bg-green-50 px-2 py-0.5 rounded-full text-xs font-medium">
                                <FaCheck size={10} /> Done
                              </span>
                            ) : (
                              <span className="inline-flex items-center gap-1 text-orange-600 bg-orange-50 px-2 py-0.5 rounded-full text-xs font-medium">
                                <FaClock size={10} /> Pending
                              </span>
                            )}
                          </td>
                          <td className="px-4 py-3 text-center text-xs text-gray-400">
                            {seoAge(p)}
                          </td>
                          <td className="px-4 py-3 text-right">
                            <button
                              onClick={() => handleRegenerateProduct(p._id)}
                              disabled={regeneratingId === p._id}
                              className="px-3 py-1 text-xs font-medium text-emerald-600 hover:text-emerald-700 bg-emerald-50 hover:bg-emerald-100 rounded-lg transition disabled:opacity-50"
                            >
                              {regeneratingId === p._id ? (
                                <FaSyncAlt className="animate-spin inline mr-1" />
                              ) : (
                                "Regen"
                              )}
                            </button>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* ─── EMBEDDINGS TAB ────────────────────────────────── */}
        {tab === "embeddings" && (
          <div className="space-y-6">
            {/* Embeddings Stats */}
            <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4">
                <div className="text-2xl font-bold text-gray-900">{embedStats?.total || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">Total Products</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-green-200 p-4">
                <div className="text-2xl font-bold text-green-600">{embedStats?.withEmbedding || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">Embedded</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-orange-200 p-4">
                <div className="text-2xl font-bold text-orange-600">{embedStats?.pending || "—"}</div>
                <div className="text-xs text-gray-500 mt-1">Pending</div>
              </div>
              <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 flex items-center justify-between">
                <div>
                  <div className="text-xs text-gray-500">API Key</div>
                  <div
                    className={`text-lg font-bold ${
                      embedStats?.available ? "text-green-600" : "text-red-500"
                    }`}
                  >
                    {embedStats?.available ? "Connected" : "Missing"}
                  </div>
                </div>
                <button
                  onClick={handleGenerateEmbeddings}
                  disabled={embedGenerating}
                  className="px-4 py-2 bg-indigo-500 text-white rounded-lg text-sm font-medium hover:bg-indigo-600 transition disabled:opacity-50 flex items-center gap-1"
                >
                  <FaSyncAlt className={embedGenerating ? "animate-spin" : ""} />
                  {embedGenerating ? "..." : "Generate All"}
                </button>
              </div>
            </div>

            {/* Info card */}
            <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl border border-indigo-200 p-6">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-lg bg-indigo-100 flex items-center justify-center flex-shrink-0">
                  <FaRobot className="text-indigo-600 text-xl" />
                </div>
                <div>
                  <h3 className="font-semibold text-indigo-900 mb-1">How Embeddings Work</h3>
                  <p className="text-sm text-indigo-700 leading-relaxed">
                    AI embeddings convert product descriptions into mathematical vectors. When you ask the
                    AI Assistant a question, it searches for products with similar vector patterns — finding
                    relevant results even when keywords don't match exactly. This powers semantic search
                    across the AI chat.
                  </p>
                  <div className="mt-3 flex items-center gap-2 text-xs text-indigo-600">
                    <FaCheck className="text-green-500" />
                    Embeddings are stored in the database and generated once
                  </div>
                  <div className="flex items-center gap-2 text-xs text-indigo-600 mt-1">
                    <FaCheck className="text-green-500" />
                    Only products with embeddings appear in AI recommendations
                  </div>
                  <div className="flex items-center gap-2 text-xs text-indigo-600 mt-1">
                    <FaBolt className="text-orange-500" />
                    "Generate All" processes products missing embeddings
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminSeoAi;
